# Generated by GhostCore OS — Phase 0 Declarative Compiler
# Profile: dev-station
# DO NOT EDIT MANUALLY — regenerate from UX Fingerprint

{ config, pkgs, lib, ... }:

{
  # ── Hostname ──────────────────────────────────────────────────────────────
  networking.hostName = "ghost-dev";

  # ── Timezone & Locale ────────────────────────────────────────────────────
  time.timeZone = "Europe/Kyiv";

  i18n.defaultLocale = "en_US.UTF-8";

  # ── Keyboard ─────────────────────────────────────────────────────────────
  services.xserver.xkb = {
    layout = "us";
    variant = "";
    options = "ctrl:nocaps";
  };

  # ── Desktop Environment / Window Manager ─────────────────────────────────
  programs.hyprland.enable = true;
  programs.hyprland.xwayland.enable = true;

  # ── Display Server ───────────────────────────────────────────────────────
  # Wayland compositor — no X11 needed

  # ── Bluetooth ────────────────────────────────────────────────────────────
  hardware.bluetooth.enable = true;

  # ── Firewall ─────────────────────────────────────────────────────────────
  networking.firewall.enable = true;

  # ── Security Hardening ───────────────────────────────────────────────────

  # ── User Account ─────────────────────────────────────────────────────────
  users.users.dev-station = {
    isNormalUser = true;
    description = "dev-station";
    extraGroups = [ "wheel" "networkmanager"  "bluetooth"   "video" "input"  ];
    shell = pkgs.zsh;
  };

  # ── Shell Configuration ──────────────────────────────────────────────────
  programs.zsh.enable = true;

  # ── System Packages ──────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [
    # Category-resolved packages
    bat
    btop
    direnv
    discord
    eza
    fastfetch
    fd
    fzf
    git
    htop
    jq
    lazygit
    neovim
    nix-direnv
    p7zip
    ripgrep
    signal-desktop
    telegram-desktop
    thunderbird
    tree
    unzip
    vscode
    zoxide

    # Window manager / DE packages
    hyprland
    waybar
    wofi
    dunst
    swaybg
    swaylock
    grim
    slurp

    # Theme packages
    catppuccin-gtk

    # Icon theme packages
    papirus-icon-theme

    # Browser
    firefox

    # Terminal emulator
    alacritty

    # Explicit allowlist
    docker
    kubectl
  ];

  # ── VPN ──────────────────────────────────────────────────────────────────
  services.tailscale.enable = true;

  # ── Git ──────────────────────────────────────────────────────────────────
  programs.git.enable = true;

  # ── Nix Settings ─────────────────────────────────────────────────────────
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # ── System State Version ─────────────────────────────────────────────────
  # This is the first generation created by GhostCore.
  system.stateVersion = "24.05";
}
